WLTS-38 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed
hmcts/ts-translation-service pull request #102
Opened 2022-09-05 10:31 UTC by mikebrownccd

https://tools.hmcts.net/jira/browse/WLTS-38
CVE-2022-34305 tomcat upgrade 9.0.65

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-11-23 09:13 UTC, dinesh1patel approved these changes
LGTM

2022-11-23 09:23 UTC, rajaram-nagarajan requested changes

2022-11-23 09:23 UTC, rajaram-nagarajan commented on config/owasp/suppressions.xml
>      <cve>CVE-2022-22976</cve>
@JamesCollettCGI  - CVE-2022-22976, CVE-2022-22978 and CVE-2021-22112 are false positives. Can you move these CVEs to false positive section and include the ticket reference?

2022-11-23 11:45 UTC, JamesCollettCGI commented on config/owasp/suppressions.xml
>      <cve>CVE-2022-22976</cve>
Moved CVE-2022-22976 , CVE-2022-22978 , CVE-2021-22112 to false positives with ticket references.

2022-11-23 12:04 UTC, rajaram-nagarajan approved these changes
LGTM

2022-11-24 13:29 UTC, dinesh1patel approved these changes
LGTM

2022-11-24 16:00 UTC, rajaram-nagarajan approved these changes
LGTM

2022-11-24 16:08 UTC, merged